### ISSUE TITLE
Apiclient only works with 10.7 or up

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-apiclient-java#124]
The next Jellyfin version, 10.7, adds new properties that are not-null. Because of this those types are not-null in the apiclient too. This will cause issues with JSON deserialization when using the apiclient with 10.6<=.

Example:
A new property in PublicSystemInfo, StartupWizardCompleted (boolean, not null) was added. If we now use `getPublicSystemInfo` in `SystemApi` it will fail for servers not emitting that field because we can't set it to a default value.

**Comment by nielsvanvelzen** [comment]
One possible solution is to require new properties in the server to be nullable. Another solution is to make literally everything nullable in the apiclient (which I'd like to avoid).

**Comment by Maxr1998** [comment]
I suppose you don't want to support multiple API versions inside the code?

**Comment by nielsvanvelzen** [comment]
We could do that by releasing model & api with a separate version scheme. But it's a lot of effort to manage and we have no openapi schema for 10.6 so we still have the issue that the apiclient is 10.7>= only.

**Comment by nielsvanvelzen** [comment]
I've created jellyfin/jellyfin#4309 to fix the PublicSystemInfo model. With this we can still connect to older Jellyfin servers so we can read their version and show an error that the server uses an unsupported version.

Ideally I'd like to support 10.6 too but I guess that's kinda hard since we need to find all new/changed properties since 10.6 to make them nullable.
