### ISSUE TITLE
Publish to JCenter

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-apiclient-java#2]
This should be published to JCenter (or similar) so it can be included as a maven or gradle dependency.

**Comment by thornbill** [comment]
As @dkanada pointed out on Riot, we should stick to a repository that is supported by F-Droid. Refs: https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L99

**Comment by thornbill** [comment]
The project can be added as a dependency from [jitpack](https://jitpack.io/#jellyfin/jellyfin-apiclient-java/master-SNAPSHOT) currently. It may still be worthwhile to publish somewhere else where we have more control over the build process in the future.

**Comment by anthonylavado** [comment]
https://bintray.com/jellyfin
:eyes:

**Comment by jbcorreia** [comment]
Can't seem to get the source for this when trying to build the androidtv repo:

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileGoogleReleaseAidl'.
> Could not resolve all task dependencies for configuration ':app:googleReleaseCompileClasspath'.
   > Could not find com.github.jellyfin.jellyfin-apiclient-java:android:master-SNAPSHOT.
     Required by:
         project :app > com.github.jellyfin:jellyfin-apiclient-java:master-SNAPSHOT:77043c2709-1
   > Could not find com.github.jellyfin.jellyfin-apiclient-java:library:master-SNAPSHOT.
     Required by:
         project :app > com.github.jellyfin:jellyfin-apiclient-java:master-SNAPSHOT:77043c2709-1

**Comment by jbcorreia** [comment]
https://jitpack.io/com/github/jellyfin/jellyfin-apiclient-java/library/master-90a2e85952-1/library-master-77043c2709-1.pom

Build failed. See the log at jitpack.io

**Comment by jbcorreia** [comment]
It's really hard to contribute if we're referencing snapshots and the repositories are not compilable.
I'd recommend to reference a release version instead of snapshots.

Joao

**Comment by nielsvanvelzen** [comment]
Bumping this to give it some attention. Would be cool if we can use versioning and a proper repository for the library.

**Comment by AndreasGB** [comment]
I did try to add versioning, but it was said that it was only wanted for releases, so that one TV release is one bump in apiclient version.

**Comment by dkanada** [comment]
That's not the case, we are just in a somewhat nebulous state because this API client is more of a placeholder until we can get at least most of the functionality generated from a specification. We could always add versioning now though.

**Comment by AndreasGB** [comment]
Hmm I remember distinctly being told to undo the version bump and reference master-snapshot again. Currently on mobile though, so I can't look up the link.

**Comment by AndreasGB** [comment]
Otoh, doesn't matter, I appreciate versioning as well

**Comment by nielsvanvelzen** [comment]
The current release (on Github) is actually called 0.4.0. I will create a PR to set a version and use 0.5.0 so we can actually publish a new version (4 commits since 0.4.0)

**Comment by thornbill** [comment]
Ok so what we want to avoid is having to constantly bump versions here and in Android TV during development. That is why the initial versioning that was added needed to be reverted.

For Android TV there is now a release branch that will use a specific release of this library. That allows the master branch of Android TV to track the master branch of the apiclient. Otherwise we would be constantly bumping versions while making changes here.
